# Generated by Django 6.0.3 on 2026-03-30 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.CreateModel(
            name='CarService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название организации')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('work_time', models.CharField(blank=True, max_length=255, verbose_name='Время работы')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг (0-5)')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Статус')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Специализация (ремонт двигателей, ходовой и т.д.)')),
                ('diagnostic_available', models.BooleanField(default=True, verbose_name='Компьютерная диагностика')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_services', to='homepage.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'СТО',
                'verbose_name_plural': 'СТО',
            },
        ),
        migrations.CreateModel(
            name='TireService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название организации')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('work_time', models.CharField(blank=True, max_length=255, verbose_name='Время работы')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг (0-5)')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Статус')),
                ('wheel_size_from', models.IntegerField(default=13, verbose_name='Размер шин от (R)')),
                ('wheel_size_to', models.IntegerField(default=22, verbose_name='Размер шин до (R)')),
                ('tire_storage', models.BooleanField(default=False, verbose_name='Сезонное хранение шин')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tire_services', to='homepage.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Шиномонтаж',
                'verbose_name_plural': 'Шиномонтаж',
            },
        ),
        migrations.CreateModel(
            name='TowTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название организации')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('work_time', models.CharField(blank=True, max_length=255, verbose_name='Время работы')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг (0-5)')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Статус')),
                ('load_capacity', models.IntegerField(default=2, verbose_name='Грузоподъемность (тонн)')),
                ('work_24_7', models.BooleanField(default=False, verbose_name='Круглосуточно')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tow_trucks', to='homepage.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Эвакуатор',
                'verbose_name_plural': 'Эвакуаторы',
            },
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
