# Generated by Django 6.0.2 on 2026-04-02 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_category_name_carservice_tireservice_towtruck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('social_vk', models.URLField(blank=True, verbose_name='ВКонтакте')),
                ('social_tg', models.URLField(blank=True, verbose_name='Telegram')),
                ('map_coordinates', models.CharField(blank=True, max_length=100, verbose_name='Координаты на карте')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название тега')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AlterField(
            model_name='carservice',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='carservice',
            name='contact_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_service', to='homepage.contactinfo', verbose_name='Контактная информация'),
        ),
        migrations.AddField(
            model_name='tireservice',
            name='contact_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_service', to='homepage.contactinfo', verbose_name='Контактная информация'),
        ),
        migrations.AddField(
            model_name='towtruck',
            name='contact_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tow_truck', to='homepage.contactinfo', verbose_name='Контактная информация'),
        ),
        migrations.AddField(
            model_name='carservice',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='car_services', to='homepage.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='tireservice',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tire_services', to='homepage.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='towtruck',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tow_trucks', to='homepage.tag', verbose_name='Теги'),
        ),
    ]
