# Generated by Django 6.0.2 on 2026-04-02 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_contactinfo_tag_alter_carservice_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='map_coordinates',
        ),
        migrations.AlterField(
            model_name='carservice',
            name='contact_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_service', to='homepage.contactinfo', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='carservice',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='carservice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tireservice',
            name='contact_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_service', to='homepage.contactinfo', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='tireservice',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='tireservice',
            name='tire_storage',
            field=models.BooleanField(default=False, verbose_name='Сезонное хранение'),
        ),
        migrations.AlterField(
            model_name='tireservice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tireservice',
            name='wheel_size_from',
            field=models.IntegerField(default=13, verbose_name='Размер шин от'),
        ),
        migrations.AlterField(
            model_name='tireservice',
            name='wheel_size_to',
            field=models.IntegerField(default=22, verbose_name='Размер шин до'),
        ),
        migrations.AlterField(
            model_name='towtruck',
            name='contact_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tow_truck', to='homepage.contactinfo', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='towtruck',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='towtruck',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
