# Generated by Django 6.0.3 on 2026-05-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_contactinfo_map_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
